/*
 * Copyright (c) 2016, 2017 Peter G. Horvath, All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

 
package com.github.dyna4jdbc.internal.nodejs.jdbc.impl;

import java.io.IOException;
import java.io.OutputStream;
import java.sql.SQLWarning;
import java.util.Arrays;
import java.util.LinkedList;
import java.util.Map;

import com.github.dyna4jdbc.internal.JDBCError;
import com.github.dyna4jdbc.internal.OutputCapturingScriptExecutor;
import com.github.dyna4jdbc.internal.ScriptExecutionException;
import com.github.dyna4jdbc.internal.config.Configuration;
import com.github.dyna4jdbc.internal.processrunner.jdbc.impl.DefaultExternalProcessScriptExecutor;


class NodeJsProcessScriptExecutor extends DefaultExternalProcessScriptExecutor {

    private static final String NODE_PROCESS_NAME = "node";
    private static final String NODE_COMMAND_LINE_ARGUMENT = "-e";

    private final String replInitScript;
    private final Configuration configuration;

    
    NodeJsProcessScriptExecutor(Configuration configuration, String replInitScript) {
        super(configuration);
        this.replInitScript = replInitScript;
        this.configuration = configuration;
    }

    @Override
    public void executeScriptUsingStreams(String script, Map<String, Object> variables,
            OutputStream stdOutOutputStream, OutputStream errorOutputStream) throws ScriptExecutionException {
        
        VariableSetScriptInvoker variableSetter = new VariableSetScriptInvoker(configuration, this);
        
        if (variables != null) {
            for (Map.Entry<String, Object> entry : variables.entrySet()) {
                String key = entry.getKey();
                Object value = entry.getValue();

                variableSetter.setVariable(key, value);
            }
        }

        super.executeScriptUsingStreams(script.replace("\n",  " ").replace("\r",  " "),
                variables, stdOutOutputStream, errorOutputStream);
    }

    private static final class VariableSetScriptInvoker extends AutoGeneratedScriptHandler {

        VariableSetScriptInvoker(Configuration configuration, OutputCapturingScriptExecutor scriptExecutor) {
            super(configuration, scriptExecutor);
        }

        private void setVariable(String variableName, Object variableValue) {

            String stringRepresentation = JavaScriptVariableConverter.convertToString(variableValue);

            String variableSetScript = String.format("%s = %s;", variableName, stringRepresentation);

            try {
                this.invokeScript(variableSetScript);

            } catch (ScriptExecutionException ex) {
                throw JDBCError.NODE_JS_INTEGRATION_ERROR.raiseUncheckedException(
                        String.format("Failed to set variable '%s' to '%s'",
                                variableName, stringRepresentation));
            }
        }

        @Override
        protected void onSingleWarning(String script, SQLWarning warning) {
            throw JDBCError.NODE_JS_INTEGRATION_ERROR.raiseUncheckedException(
                    warning,
                    "stdERR write while invoking dyna4JDBC auto-generated JavaScript intended to set a variable. "
                    + "Script is: " + script);
        }

        @Override
        protected void onMultipleWarnings(String script, LinkedList<SQLWarning> warningList) {
            throw JDBCError.NODE_JS_INTEGRATION_ERROR.raiseUncheckedExceptionWithSuppressed(warningList,
                    "stdERR write while invoking dyna4JDBC auto-generated JavaScript intended to set a variable. "
                    + "Script is: " + script);
        }
    }


    @Override
    protected void onProcessNotRunningBeforeDispatch(String script) throws ScriptExecutionException {
        throw new ScriptExecutionException(
                "Node.js process exited unexpectedly! Cannot execute script: " + script);

    }


    @Override
    protected Process createProcess(String script, Map<String, Object> variables) throws IOException {

        try {
            ProcessBuilder processBuilder = new ProcessBuilder();
            processBuilder.command(Arrays.asList(NODE_PROCESS_NAME, NODE_COMMAND_LINE_ARGUMENT, replInitScript));

            if (variables != null) {

                Map<String, String> environment = processBuilder.environment();

                variables.entrySet().forEach(entry -> {
                    String key = entry.getKey();
                    Object value = entry.getValue();

                    String valueString = String.valueOf(value);

                    environment.put(key, valueString);
                });
            }

            return processBuilder.start();
        } catch (IOException ioEx) {
            throw JDBCError.NODE_JS_INTEGRATION_ERROR.raiseUncheckedException(ioEx,
                    String.format("Failed to launch Node.js process \"%s\": %s",
                            NODE_PROCESS_NAME, ioEx.getMessage()));
        }
    }

}
